spring:
  application:
    name: h-ai-agent
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://47.118.84.108:5432/shopmateagent

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hsc.haiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
