spring:
  application:
    name: h-ai-agent
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://47.118.84.108:5432/shopmateagent
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  ai:
    mcp:
      client:
        enabled: false
  #        sse:
#          connections:
#            server1:
#              url: http://localhost:8127

#        init-timeout: 30s  # 给单元测试留出足够的启动缓冲时间，防止因卡顿导致握手超时
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
  mail:
    # 1. 邮件服务器的“地址”。QQ邮箱的发送服务器固定为 smtp.qq.com
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          # 4. 开启 SMTP 身份验证。必须为 true，告诉QQ服务器“我是带了账号密码来登录的”
          auth: true
          starttls:
            # 5. 开启 TLS 加密传输。必须为 true，确保你的邮件内容在网络传输过程中不会被黑客窃听
            enable: true
app:
  jwt:
    secret: SHOPMATE_AI_AGENT_JWT_SECRET_KEY_2026_07_01_SECURE
    expiration: 86400000
  github:
    repo: alibaba/spring-ai-alibaba
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hsc.haiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
